// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/v1/watch_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authzed.Api.V1 {

  /// <summary>Holder for reflection information generated from authzed/api/v1/watch_service.proto</summary>
  public static partial class WatchServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for authzed/api/v1/watch_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatchServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhdXRoemVkL2FwaS92MS93YXRjaF9zZXJ2aWNlLnByb3RvEg5hdXRoemVk",
            "LmFwaS52MRocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5wcm90bxocZ29vZ2xl",
            "L3Byb3RvYnVmL3N0cnVjdC5wcm90bxoXdmFsaWRhdGUvdmFsaWRhdGUucHJv",
            "dG8aGWF1dGh6ZWQvYXBpL3YxL2NvcmUucHJvdG8aJ2F1dGh6ZWQvYXBpL3Yx",
            "L3Blcm1pc3Npb25fc2VydmljZS5wcm90byLKAgoMV2F0Y2hSZXF1ZXN0EoMB",
            "ChVvcHRpb25hbF9vYmplY3RfdHlwZXMYASADKAlCT/pCTJIBSQgAIkVyQyiA",
            "ATI+XihbYS16XVthLXowLTlfXXsxLDYyfVthLXowLTldLykqW2Etel1bYS16",
            "MC05X117MSw2Mn1bYS16MC05XSRSE29wdGlvbmFsT2JqZWN0VHlwZXMSTAoV",
            "b3B0aW9uYWxfc3RhcnRfY3Vyc29yGAIgASgLMhguYXV0aHplZC5hcGkudjEu",
            "WmVkVG9rZW5SE29wdGlvbmFsU3RhcnRDdXJzb3ISZgodb3B0aW9uYWxfcmVs",
            "YXRpb25zaGlwX2ZpbHRlcnMYAyADKAsyIi5hdXRoemVkLmFwaS52MS5SZWxh",
            "dGlvbnNoaXBGaWx0ZXJSG29wdGlvbmFsUmVsYXRpb25zaGlwRmlsdGVycyLt",
            "AQoNV2F0Y2hSZXNwb25zZRI8Cgd1cGRhdGVzGAEgAygLMiIuYXV0aHplZC5h",
            "cGkudjEuUmVsYXRpb25zaGlwVXBkYXRlUgd1cGRhdGVzEkEKD2NoYW5nZXNf",
            "dGhyb3VnaBgCIAEoCzIYLmF1dGh6ZWQuYXBpLnYxLlplZFRva2VuUg5jaGFu",
            "Z2VzVGhyb3VnaBJbCh1vcHRpb25hbF90cmFuc2FjdGlvbl9tZXRhZGF0YRgD",
            "IAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RSG29wdGlvbmFsVHJhbnNh",
            "Y3Rpb25NZXRhZGF0YTJsCgxXYXRjaFNlcnZpY2USXAoFV2F0Y2gSHC5hdXRo",
            "emVkLmFwaS52MS5XYXRjaFJlcXVlc3QaHS5hdXRoemVkLmFwaS52MS5XYXRj",
            "aFJlc3BvbnNlIhSC0+STAg4iCS92MS93YXRjaDoBKjABQkoKEmNvbS5hdXRo",
            "emVkLmFwaS52MVABWjJnaXRodWIuY29tL2F1dGh6ZWQvYXV0aHplZC1nby9w",
            "cm90by9hdXRoemVkL2FwaS92MWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Authzed.Api.V1.CoreReflection.Descriptor, global::Authzed.Api.V1.PermissionServiceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.WatchRequest), global::Authzed.Api.V1.WatchRequest.Parser, new[]{ "OptionalObjectTypes", "OptionalStartCursor", "OptionalRelationshipFilters" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.WatchResponse), global::Authzed.Api.V1.WatchResponse.Parser, new[]{ "Updates", "ChangesThrough", "OptionalTransactionMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// WatchRequest specifies the object definitions for which we want to start
  /// watching mutations, and an optional start snapshot for when to start
  /// watching.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchRequest : pb::IMessage<WatchRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchRequest> _parser = new pb::MessageParser<WatchRequest>(() => new WatchRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.WatchServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest(WatchRequest other) : this() {
      optionalObjectTypes_ = other.optionalObjectTypes_.Clone();
      optionalStartCursor_ = other.optionalStartCursor_ != null ? other.optionalStartCursor_.Clone() : null;
      optionalRelationshipFilters_ = other.optionalRelationshipFilters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest Clone() {
      return new WatchRequest(this);
    }

    /// <summary>Field number for the "optional_object_types" field.</summary>
    public const int OptionalObjectTypesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_optionalObjectTypes_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> optionalObjectTypes_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// optional_object_types is a filter of resource object types to watch for changes.
    /// If specified, only changes to the specified object types will be returned and
    /// optional_relationship_filters cannot be used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> OptionalObjectTypes {
      get { return optionalObjectTypes_; }
    }

    /// <summary>Field number for the "optional_start_cursor" field.</summary>
    public const int OptionalStartCursorFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken optionalStartCursor_;
    /// <summary>
    /// optional_start_cursor is the ZedToken holding the point-in-time at
    /// which to start watching for changes.
    /// If not specified, the watch will begin at the current head revision
    /// of the datastore, returning any updates that occur after the caller
    /// makes the request.
    /// Note that if this cursor references a point-in-time containing data
    /// that has been garbage collected, an error will be returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken OptionalStartCursor {
      get { return optionalStartCursor_; }
      set {
        optionalStartCursor_ = value;
      }
    }

    /// <summary>Field number for the "optional_relationship_filters" field.</summary>
    public const int OptionalRelationshipFiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.RelationshipFilter> _repeated_optionalRelationshipFilters_codec
        = pb::FieldCodec.ForMessage(26, global::Authzed.Api.V1.RelationshipFilter.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter> optionalRelationshipFilters_ = new pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter>();
    /// <summary>
    /// optional_relationship_filters, if specified, indicates the
    /// filter(s) to apply to each relationship to be returned by watch.
    /// The relationship will be returned as long as at least one filter matches,
    /// this allows clients to match relationships on multiple filters on a single watch call.
    /// If specified, optional_object_types cannot be used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter> OptionalRelationshipFilters {
      get { return optionalRelationshipFilters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!optionalObjectTypes_.Equals(other.optionalObjectTypes_)) return false;
      if (!object.Equals(OptionalStartCursor, other.OptionalStartCursor)) return false;
      if(!optionalRelationshipFilters_.Equals(other.optionalRelationshipFilters_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= optionalObjectTypes_.GetHashCode();
      if (optionalStartCursor_ != null) hash ^= OptionalStartCursor.GetHashCode();
      hash ^= optionalRelationshipFilters_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      optionalObjectTypes_.WriteTo(output, _repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartCursor);
      }
      optionalRelationshipFilters_.WriteTo(output, _repeated_optionalRelationshipFilters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      optionalObjectTypes_.WriteTo(ref output, _repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartCursor);
      }
      optionalRelationshipFilters_.WriteTo(ref output, _repeated_optionalRelationshipFilters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += optionalObjectTypes_.CalculateSize(_repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalStartCursor);
      }
      size += optionalRelationshipFilters_.CalculateSize(_repeated_optionalRelationshipFilters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchRequest other) {
      if (other == null) {
        return;
      }
      optionalObjectTypes_.Add(other.optionalObjectTypes_);
      if (other.optionalStartCursor_ != null) {
        if (optionalStartCursor_ == null) {
          OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
        }
        OptionalStartCursor.MergeFrom(other.OptionalStartCursor);
      }
      optionalRelationshipFilters_.Add(other.optionalRelationshipFilters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            optionalObjectTypes_.AddEntriesFrom(input, _repeated_optionalObjectTypes_codec);
            break;
          }
          case 18: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
          case 26: {
            optionalRelationshipFilters_.AddEntriesFrom(input, _repeated_optionalRelationshipFilters_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            optionalObjectTypes_.AddEntriesFrom(ref input, _repeated_optionalObjectTypes_codec);
            break;
          }
          case 18: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
          case 26: {
            optionalRelationshipFilters_.AddEntriesFrom(ref input, _repeated_optionalRelationshipFilters_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// WatchResponse contains all tuple modification events in ascending
  /// timestamp order, from the requested start snapshot to a snapshot
  /// encoded in the watch response. The client can use the snapshot to resume
  /// watching where the previous watch response left off.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchResponse : pb::IMessage<WatchResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchResponse> _parser = new pb::MessageParser<WatchResponse>(() => new WatchResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.WatchServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse(WatchResponse other) : this() {
      updates_ = other.updates_.Clone();
      changesThrough_ = other.changesThrough_ != null ? other.changesThrough_.Clone() : null;
      optionalTransactionMetadata_ = other.optionalTransactionMetadata_ != null ? other.optionalTransactionMetadata_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse Clone() {
      return new WatchResponse(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.RelationshipUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Authzed.Api.V1.RelationshipUpdate.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate> updates_ = new pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate>();
    /// <summary>
    /// updates are the RelationshipUpdate events that have occurred since the
    /// last watch response.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate> Updates {
      get { return updates_; }
    }

    /// <summary>Field number for the "changes_through" field.</summary>
    public const int ChangesThroughFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken changesThrough_;
    /// <summary>
    /// changes_through is the ZedToken that represents the point in time
    /// that the watch response is current through. This token can be used
    /// in a subsequent WatchRequest to resume watching from this point.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken ChangesThrough {
      get { return changesThrough_; }
      set {
        changesThrough_ = value;
      }
    }

    /// <summary>Field number for the "optional_transaction_metadata" field.</summary>
    public const int OptionalTransactionMetadataFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Struct optionalTransactionMetadata_;
    /// <summary>
    /// optional_transaction_metadata is an optional field that returns the transaction metadata
    /// given to SpiceDB during the transaction that produced the changes in this response.
    /// This field may not exist if no transaction metadata was provided.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct OptionalTransactionMetadata {
      get { return optionalTransactionMetadata_; }
      set {
        optionalTransactionMetadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      if (!object.Equals(ChangesThrough, other.ChangesThrough)) return false;
      if (!object.Equals(OptionalTransactionMetadata, other.OptionalTransactionMetadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (changesThrough_ != null) hash ^= ChangesThrough.GetHashCode();
      if (optionalTransactionMetadata_ != null) hash ^= OptionalTransactionMetadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      updates_.WriteTo(output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OptionalTransactionMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      updates_.WriteTo(ref output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OptionalTransactionMetadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (changesThrough_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalTransactionMetadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchResponse other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      if (other.changesThrough_ != null) {
        if (changesThrough_ == null) {
          ChangesThrough = new global::Authzed.Api.V1.ZedToken();
        }
        ChangesThrough.MergeFrom(other.ChangesThrough);
      }
      if (other.optionalTransactionMetadata_ != null) {
        if (optionalTransactionMetadata_ == null) {
          OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        OptionalTransactionMetadata.MergeFrom(other.OptionalTransactionMetadata);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
          case 26: {
            if (optionalTransactionMetadata_ == null) {
              OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(OptionalTransactionMetadata);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            updates_.AddEntriesFrom(ref input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
          case 26: {
            if (optionalTransactionMetadata_ == null) {
              OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(OptionalTransactionMetadata);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
