// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/v1/watch_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authzed.Api.V1 {

  /// <summary>Holder for reflection information generated from authzed/api/v1/watch_service.proto</summary>
  public static partial class WatchServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for authzed/api/v1/watch_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatchServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJhdXRoemVkL2FwaS92MS93YXRjaF9zZXJ2aWNlLnByb3RvEg5hdXRoemVk",
            "LmFwaS52MRoZYXV0aHplZC9hcGkvdjEvY29yZS5wcm90bxonYXV0aHplZC9h",
            "cGkvdjEvcGVybWlzc2lvbl9zZXJ2aWNlLnByb3RvGhtidWYvdmFsaWRhdGUv",
            "dmFsaWRhdGUucHJvdG8aHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8a",
            "HGdvb2dsZS9wcm90b2J1Zi9zdHJ1Y3QucHJvdG8aLnByb3RvYy1nZW4tb3Bl",
            "bmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJvdG8aF3ZhbGlkYXRlL3Zh",
            "bGlkYXRlLnByb3RvIukDCgxXYXRjaFJlcXVlc3QS0wEKFW9wdGlvbmFsX29i",
            "amVjdF90eXBlcxgBIAMoCUKeAfpCTJIBSQgAIkVyQyiAATI+XihbYS16XVth",
            "LXowLTlfXXsxLDYyfVthLXowLTldLykqW2Etel1bYS16MC05X117MSw2Mn1b",
            "YS16MC05XSS6SEySAUkIACJFckMogAEyPl4oW2Etel1bYS16MC05X117MSw2",
            "Mn1bYS16MC05XS8pKlthLXpdW2EtejAtOV9dezEsNjJ9W2EtejAtOV0kUhNv",
            "cHRpb25hbE9iamVjdFR5cGVzEkwKFW9wdGlvbmFsX3N0YXJ0X2N1cnNvchgC",
            "IAEoCzIYLmF1dGh6ZWQuYXBpLnYxLlplZFRva2VuUhNvcHRpb25hbFN0YXJ0",
            "Q3Vyc29yEmYKHW9wdGlvbmFsX3JlbGF0aW9uc2hpcF9maWx0ZXJzGAMgAygL",
            "MiIuYXV0aHplZC5hcGkudjEuUmVsYXRpb25zaGlwRmlsdGVyUhtvcHRpb25h",
            "bFJlbGF0aW9uc2hpcEZpbHRlcnMSTQoVb3B0aW9uYWxfdXBkYXRlX2tpbmRz",
            "GAQgAygOMhkuYXV0aHplZC5hcGkudjEuV2F0Y2hLaW5kUhNvcHRpb25hbFVw",
            "ZGF0ZUtpbmRzIogDCg1XYXRjaFJlc3BvbnNlEjwKB3VwZGF0ZXMYASADKAsy",
            "Ii5hdXRoemVkLmFwaS52MS5SZWxhdGlvbnNoaXBVcGRhdGVSB3VwZGF0ZXMS",
            "QQoPY2hhbmdlc190aHJvdWdoGAIgASgLMhguYXV0aHplZC5hcGkudjEuWmVk",
            "VG9rZW5SDmNoYW5nZXNUaHJvdWdoElsKHW9wdGlvbmFsX3RyYW5zYWN0aW9u",
            "X21ldGFkYXRhGAMgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdFIbb3B0",
            "aW9uYWxUcmFuc2FjdGlvbk1ldGFkYXRhEiUKDnNjaGVtYV91cGRhdGVkGAQg",
            "ASgIUg1zY2hlbWFVcGRhdGVkEiMKDWlzX2NoZWNrcG9pbnQYBSABKAhSDGlz",
            "Q2hlY2twb2ludBJNChZmdWxsX3JldmlzaW9uX21ldGFkYXRhGAYgAygLMhcu",
            "Z29vZ2xlLnByb3RvYnVmLlN0cnVjdFIUZnVsbFJldmlzaW9uTWV0YWRhdGEq",
            "nwEKCVdhdGNoS2luZBIaChZXQVRDSF9LSU5EX1VOU1BFQ0lGSUVEEAASKwon",
            "V0FUQ0hfS0lORF9JTkNMVURFX1JFTEFUSU9OU0hJUF9VUERBVEVTEAESJQoh",
            "V0FUQ0hfS0lORF9JTkNMVURFX1NDSEVNQV9VUERBVEVTEAISIgoeV0FUQ0hf",
            "S0lORF9JTkNMVURFX0NIRUNLUE9JTlRTEAMydgoMV2F0Y2hTZXJ2aWNlEmYK",
            "BVdhdGNoEhwuYXV0aHplZC5hcGkudjEuV2F0Y2hSZXF1ZXN0Gh0uYXV0aHpl",
            "ZC5hcGkudjEuV2F0Y2hSZXNwb25zZSIekkEHCgVXYXRjaILT5JMCDiIJL3Yx",
            "L3dhdGNoOgEqMAFCSgoSY29tLmF1dGh6ZWQuYXBpLnYxUAFaMmdpdGh1Yi5j",
            "b20vYXV0aHplZC9hdXRoemVkLWdvL3Byb3RvL2F1dGh6ZWQvYXBpL3YxYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Authzed.Api.V1.CoreReflection.Descriptor, global::Authzed.Api.V1.PermissionServiceReflection.Descriptor, global::Buf.Validate.ValidateReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Authzed.Api.V1.WatchKind), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.WatchRequest), global::Authzed.Api.V1.WatchRequest.Parser, new[]{ "OptionalObjectTypes", "OptionalStartCursor", "OptionalRelationshipFilters", "OptionalUpdateKinds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1.WatchResponse), global::Authzed.Api.V1.WatchResponse.Parser, new[]{ "Updates", "ChangesThrough", "OptionalTransactionMetadata", "SchemaUpdated", "IsCheckpoint", "FullRevisionMetadata" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WatchKind {
    /// <summary>
    /// Default, just relationship updates (for backwards compatibility)
    /// </summary>
    [pbr::OriginalName("WATCH_KIND_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("WATCH_KIND_INCLUDE_RELATIONSHIP_UPDATES")] IncludeRelationshipUpdates = 1,
    [pbr::OriginalName("WATCH_KIND_INCLUDE_SCHEMA_UPDATES")] IncludeSchemaUpdates = 2,
    [pbr::OriginalName("WATCH_KIND_INCLUDE_CHECKPOINTS")] IncludeCheckpoints = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// WatchRequest specifies what mutations to watch for, and an optional start point for when to start
  /// watching.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchRequest : pb::IMessage<WatchRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchRequest> _parser = new pb::MessageParser<WatchRequest>(() => new WatchRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.WatchServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest(WatchRequest other) : this() {
      optionalObjectTypes_ = other.optionalObjectTypes_.Clone();
      optionalStartCursor_ = other.optionalStartCursor_ != null ? other.optionalStartCursor_.Clone() : null;
      optionalRelationshipFilters_ = other.optionalRelationshipFilters_.Clone();
      optionalUpdateKinds_ = other.optionalUpdateKinds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchRequest Clone() {
      return new WatchRequest(this);
    }

    /// <summary>Field number for the "optional_object_types" field.</summary>
    public const int OptionalObjectTypesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_optionalObjectTypes_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> optionalObjectTypes_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// optional_object_types is a filter of resource object types to watch for relationship changes.
    /// If specified, only changes to the specified object types will be returned and
    /// optional_relationship_filters cannot be used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> OptionalObjectTypes {
      get { return optionalObjectTypes_; }
    }

    /// <summary>Field number for the "optional_start_cursor" field.</summary>
    public const int OptionalStartCursorFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken optionalStartCursor_;
    /// <summary>
    /// optional_start_cursor is the ZedToken holding the point-in-time at
    /// which to start watching for changes.
    /// If not specified, the watch will start from the current SpiceDB revision time of the request ("head revision").
    /// Note that if this cursor references a point-in-time containing data
    /// that has been garbage collected, an error will be returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken OptionalStartCursor {
      get { return optionalStartCursor_; }
      set {
        optionalStartCursor_ = value;
      }
    }

    /// <summary>Field number for the "optional_relationship_filters" field.</summary>
    public const int OptionalRelationshipFiltersFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.RelationshipFilter> _repeated_optionalRelationshipFilters_codec
        = pb::FieldCodec.ForMessage(26, global::Authzed.Api.V1.RelationshipFilter.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter> optionalRelationshipFilters_ = new pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter>();
    /// <summary>
    /// optional_relationship_filters, if specified, indicates the
    /// filter(s) to apply to each relationship to be returned by watch.
    /// The relationship will be returned as long as at least one filter matches,
    /// this allows clients to match relationships on multiple filters on a single watch call.
    /// If specified, optional_object_types cannot be used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.RelationshipFilter> OptionalRelationshipFilters {
      get { return optionalRelationshipFilters_; }
    }

    /// <summary>Field number for the "optional_update_kinds" field.</summary>
    public const int OptionalUpdateKindsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.WatchKind> _repeated_optionalUpdateKinds_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::Authzed.Api.V1.WatchKind) x);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.WatchKind> optionalUpdateKinds_ = new pbc::RepeatedField<global::Authzed.Api.V1.WatchKind>();
    /// <summary>
    /// optional_update_kinds, if specified, indicates what kinds of mutations to include.
    /// If your SpiceDB instance is running behind a proxy that aborts idle connections,
    /// we recommend including Checkpoints to keep the stream alive even when there are no changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.WatchKind> OptionalUpdateKinds {
      get { return optionalUpdateKinds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!optionalObjectTypes_.Equals(other.optionalObjectTypes_)) return false;
      if (!object.Equals(OptionalStartCursor, other.OptionalStartCursor)) return false;
      if(!optionalRelationshipFilters_.Equals(other.optionalRelationshipFilters_)) return false;
      if(!optionalUpdateKinds_.Equals(other.optionalUpdateKinds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= optionalObjectTypes_.GetHashCode();
      if (optionalStartCursor_ != null) hash ^= OptionalStartCursor.GetHashCode();
      hash ^= optionalRelationshipFilters_.GetHashCode();
      hash ^= optionalUpdateKinds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      optionalObjectTypes_.WriteTo(output, _repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartCursor);
      }
      optionalRelationshipFilters_.WriteTo(output, _repeated_optionalRelationshipFilters_codec);
      optionalUpdateKinds_.WriteTo(output, _repeated_optionalUpdateKinds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      optionalObjectTypes_.WriteTo(ref output, _repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartCursor);
      }
      optionalRelationshipFilters_.WriteTo(ref output, _repeated_optionalRelationshipFilters_codec);
      optionalUpdateKinds_.WriteTo(ref output, _repeated_optionalUpdateKinds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += optionalObjectTypes_.CalculateSize(_repeated_optionalObjectTypes_codec);
      if (optionalStartCursor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalStartCursor);
      }
      size += optionalRelationshipFilters_.CalculateSize(_repeated_optionalRelationshipFilters_codec);
      size += optionalUpdateKinds_.CalculateSize(_repeated_optionalUpdateKinds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchRequest other) {
      if (other == null) {
        return;
      }
      optionalObjectTypes_.Add(other.optionalObjectTypes_);
      if (other.optionalStartCursor_ != null) {
        if (optionalStartCursor_ == null) {
          OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
        }
        OptionalStartCursor.MergeFrom(other.OptionalStartCursor);
      }
      optionalRelationshipFilters_.Add(other.optionalRelationshipFilters_);
      optionalUpdateKinds_.Add(other.optionalUpdateKinds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            optionalObjectTypes_.AddEntriesFrom(input, _repeated_optionalObjectTypes_codec);
            break;
          }
          case 18: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
          case 26: {
            optionalRelationshipFilters_.AddEntriesFrom(input, _repeated_optionalRelationshipFilters_codec);
            break;
          }
          case 34:
          case 32: {
            optionalUpdateKinds_.AddEntriesFrom(input, _repeated_optionalUpdateKinds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            optionalObjectTypes_.AddEntriesFrom(ref input, _repeated_optionalObjectTypes_codec);
            break;
          }
          case 18: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
          case 26: {
            optionalRelationshipFilters_.AddEntriesFrom(ref input, _repeated_optionalRelationshipFilters_codec);
            break;
          }
          case 34:
          case 32: {
            optionalUpdateKinds_.AddEntriesFrom(ref input, _repeated_optionalUpdateKinds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// WatchResponse contains all mutation events in ascending timestamp order.
  /// This excludes relationships that were deleted because they expired.
  /// The response includes a field that can be used to resume
  /// watching from that point.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WatchResponse : pb::IMessage<WatchResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchResponse> _parser = new pb::MessageParser<WatchResponse>(() => new WatchResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1.WatchServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse(WatchResponse other) : this() {
      updates_ = other.updates_.Clone();
      changesThrough_ = other.changesThrough_ != null ? other.changesThrough_.Clone() : null;
      optionalTransactionMetadata_ = other.optionalTransactionMetadata_ != null ? other.optionalTransactionMetadata_.Clone() : null;
      schemaUpdated_ = other.schemaUpdated_;
      isCheckpoint_ = other.isCheckpoint_;
      fullRevisionMetadata_ = other.fullRevisionMetadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResponse Clone() {
      return new WatchResponse(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1.RelationshipUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Authzed.Api.V1.RelationshipUpdate.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate> updates_ = new pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate>();
    /// <summary>
    /// updates are the RelationshipUpdate events that have occurred since the
    /// call was made, or since the point in time specified by changes_through.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1.RelationshipUpdate> Updates {
      get { return updates_; }
    }

    /// <summary>Field number for the "changes_through" field.</summary>
    public const int ChangesThroughFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken changesThrough_;
    /// <summary>
    /// changes_through is the ZedToken that represents the point in time
    /// that the watch response is current through. This token can be used
    /// in a subsequent WatchRequest to resume watching from this point.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken ChangesThrough {
      get { return changesThrough_; }
      set {
        changesThrough_ = value;
      }
    }

    /// <summary>Field number for the "optional_transaction_metadata" field.</summary>
    public const int OptionalTransactionMetadataFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Struct optionalTransactionMetadata_;
    /// <summary>
    /// optional_transaction_metadata is an optional field that returns the transaction metadata
    /// given to SpiceDB during the transaction that produced the changes in this response.
    /// This field may not exist if no transaction metadata was provided, or if multiple pieces
    /// of metadata were found during the transaction (in which case it is ambiguous which to return).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Struct OptionalTransactionMetadata {
      get { return optionalTransactionMetadata_; }
      set {
        optionalTransactionMetadata_ = value;
      }
    }

    /// <summary>Field number for the "schema_updated" field.</summary>
    public const int SchemaUpdatedFieldNumber = 4;
    private bool schemaUpdated_;
    /// <summary>
    /// schema_updated, if true, indicates that the schema was changed in this revision.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SchemaUpdated {
      get { return schemaUpdated_; }
      set {
        schemaUpdated_ = value;
      }
    }

    /// <summary>Field number for the "is_checkpoint" field.</summary>
    public const int IsCheckpointFieldNumber = 5;
    private bool isCheckpoint_;
    /// <summary>
    /// is_checkpoint, if true, indicates that a checkpoint was reached.
    /// A checkpoint indicates that the server guarantees that the client
    /// will not observe any changes at a revision below or equal to the revision in this response.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCheckpoint {
      get { return isCheckpoint_; }
      set {
        isCheckpoint_ = value;
      }
    }

    /// <summary>Field number for the "full_revision_metadata" field.</summary>
    public const int FullRevisionMetadataFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Struct> _repeated_fullRevisionMetadata_codec
        = pb::FieldCodec.ForMessage(50, global::Google.Protobuf.WellKnownTypes.Struct.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct> fullRevisionMetadata_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct>();
    /// <summary>
    /// full_revision_metadata contains all transaction metadata given to SpiceDB during the
    /// revision that produced the changes in this response. Some datastores (such as CockroachDB)
    /// can "merge" multiple transactions into a single revision (if the changes occurred concurrently),
    /// so this field is a list of all transaction metadata seen during the revision.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Struct> FullRevisionMetadata {
      get { return fullRevisionMetadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      if (!object.Equals(ChangesThrough, other.ChangesThrough)) return false;
      if (!object.Equals(OptionalTransactionMetadata, other.OptionalTransactionMetadata)) return false;
      if (SchemaUpdated != other.SchemaUpdated) return false;
      if (IsCheckpoint != other.IsCheckpoint) return false;
      if(!fullRevisionMetadata_.Equals(other.fullRevisionMetadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (changesThrough_ != null) hash ^= ChangesThrough.GetHashCode();
      if (optionalTransactionMetadata_ != null) hash ^= OptionalTransactionMetadata.GetHashCode();
      if (SchemaUpdated != false) hash ^= SchemaUpdated.GetHashCode();
      if (IsCheckpoint != false) hash ^= IsCheckpoint.GetHashCode();
      hash ^= fullRevisionMetadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      updates_.WriteTo(output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OptionalTransactionMetadata);
      }
      if (SchemaUpdated != false) {
        output.WriteRawTag(32);
        output.WriteBool(SchemaUpdated);
      }
      if (IsCheckpoint != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsCheckpoint);
      }
      fullRevisionMetadata_.WriteTo(output, _repeated_fullRevisionMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      updates_.WriteTo(ref output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OptionalTransactionMetadata);
      }
      if (SchemaUpdated != false) {
        output.WriteRawTag(32);
        output.WriteBool(SchemaUpdated);
      }
      if (IsCheckpoint != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsCheckpoint);
      }
      fullRevisionMetadata_.WriteTo(ref output, _repeated_fullRevisionMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (changesThrough_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangesThrough);
      }
      if (optionalTransactionMetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalTransactionMetadata);
      }
      if (SchemaUpdated != false) {
        size += 1 + 1;
      }
      if (IsCheckpoint != false) {
        size += 1 + 1;
      }
      size += fullRevisionMetadata_.CalculateSize(_repeated_fullRevisionMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchResponse other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      if (other.changesThrough_ != null) {
        if (changesThrough_ == null) {
          ChangesThrough = new global::Authzed.Api.V1.ZedToken();
        }
        ChangesThrough.MergeFrom(other.ChangesThrough);
      }
      if (other.optionalTransactionMetadata_ != null) {
        if (optionalTransactionMetadata_ == null) {
          OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
        }
        OptionalTransactionMetadata.MergeFrom(other.OptionalTransactionMetadata);
      }
      if (other.SchemaUpdated != false) {
        SchemaUpdated = other.SchemaUpdated;
      }
      if (other.IsCheckpoint != false) {
        IsCheckpoint = other.IsCheckpoint;
      }
      fullRevisionMetadata_.Add(other.fullRevisionMetadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
          case 26: {
            if (optionalTransactionMetadata_ == null) {
              OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(OptionalTransactionMetadata);
            break;
          }
          case 32: {
            SchemaUpdated = input.ReadBool();
            break;
          }
          case 40: {
            IsCheckpoint = input.ReadBool();
            break;
          }
          case 50: {
            fullRevisionMetadata_.AddEntriesFrom(input, _repeated_fullRevisionMetadata_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            updates_.AddEntriesFrom(ref input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
          case 26: {
            if (optionalTransactionMetadata_ == null) {
              OptionalTransactionMetadata = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            input.ReadMessage(OptionalTransactionMetadata);
            break;
          }
          case 32: {
            SchemaUpdated = input.ReadBool();
            break;
          }
          case 40: {
            IsCheckpoint = input.ReadBool();
            break;
          }
          case 50: {
            fullRevisionMetadata_.AddEntriesFrom(ref input, _repeated_fullRevisionMetadata_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
