// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/v1alpha1/schema.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Authzed.Api.V1Alpha1 {
  /// <summary>
  /// SchemaService implements operations on a Permissions System's Schema.
  /// </summary>
  public static partial class SchemaService
  {
    static readonly string __ServiceName = "authzed.api.v1alpha1.SchemaService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.V1Alpha1.ReadSchemaRequest> __Marshaller_authzed_api_v1alpha1_ReadSchemaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.V1Alpha1.ReadSchemaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.V1Alpha1.ReadSchemaResponse> __Marshaller_authzed_api_v1alpha1_ReadSchemaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.V1Alpha1.ReadSchemaResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.V1Alpha1.WriteSchemaRequest> __Marshaller_authzed_api_v1alpha1_WriteSchemaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.V1Alpha1.WriteSchemaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.V1Alpha1.WriteSchemaResponse> __Marshaller_authzed_api_v1alpha1_WriteSchemaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.V1Alpha1.WriteSchemaResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Authzed.Api.V1Alpha1.ReadSchemaRequest, global::Authzed.Api.V1Alpha1.ReadSchemaResponse> __Method_ReadSchema = new grpc::Method<global::Authzed.Api.V1Alpha1.ReadSchemaRequest, global::Authzed.Api.V1Alpha1.ReadSchemaResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadSchema",
        __Marshaller_authzed_api_v1alpha1_ReadSchemaRequest,
        __Marshaller_authzed_api_v1alpha1_ReadSchemaResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Authzed.Api.V1Alpha1.WriteSchemaRequest, global::Authzed.Api.V1Alpha1.WriteSchemaResponse> __Method_WriteSchema = new grpc::Method<global::Authzed.Api.V1Alpha1.WriteSchemaRequest, global::Authzed.Api.V1Alpha1.WriteSchemaResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "WriteSchema",
        __Marshaller_authzed_api_v1alpha1_WriteSchemaRequest,
        __Marshaller_authzed_api_v1alpha1_WriteSchemaResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Authzed.Api.V1Alpha1.SchemaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SchemaService</summary>
    public partial class SchemaServiceClient : grpc::ClientBase<SchemaServiceClient>
    {
      /// <summary>Creates a new client for SchemaService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SchemaServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SchemaService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SchemaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SchemaServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SchemaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Read returns the current Object Definitions for a Permissions System.
      ///
      /// Errors include:
      /// - INVALID_ARGUMENT: a provided value has failed to semantically validate
      /// - NOT_FOUND: one of the Object Definitions being requested does not exist
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Authzed.Api.V1Alpha1.ReadSchemaResponse ReadSchema(global::Authzed.Api.V1Alpha1.ReadSchemaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadSchema(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Read returns the current Object Definitions for a Permissions System.
      ///
      /// Errors include:
      /// - INVALID_ARGUMENT: a provided value has failed to semantically validate
      /// - NOT_FOUND: one of the Object Definitions being requested does not exist
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Authzed.Api.V1Alpha1.ReadSchemaResponse ReadSchema(global::Authzed.Api.V1Alpha1.ReadSchemaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadSchema, null, options, request);
      }
      /// <summary>
      /// Read returns the current Object Definitions for a Permissions System.
      ///
      /// Errors include:
      /// - INVALID_ARGUMENT: a provided value has failed to semantically validate
      /// - NOT_FOUND: one of the Object Definitions being requested does not exist
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Authzed.Api.V1Alpha1.ReadSchemaResponse> ReadSchemaAsync(global::Authzed.Api.V1Alpha1.ReadSchemaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadSchemaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Read returns the current Object Definitions for a Permissions System.
      ///
      /// Errors include:
      /// - INVALID_ARGUMENT: a provided value has failed to semantically validate
      /// - NOT_FOUND: one of the Object Definitions being requested does not exist
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Authzed.Api.V1Alpha1.ReadSchemaResponse> ReadSchemaAsync(global::Authzed.Api.V1Alpha1.ReadSchemaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadSchema, null, options, request);
      }
      /// <summary>
      /// Write overwrites the current Object Definitions for a Permissions System.
      ///
      /// Any Object Definitions that exist, but are not included will be deleted.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Authzed.Api.V1Alpha1.WriteSchemaResponse WriteSchema(global::Authzed.Api.V1Alpha1.WriteSchemaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WriteSchema(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Write overwrites the current Object Definitions for a Permissions System.
      ///
      /// Any Object Definitions that exist, but are not included will be deleted.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Authzed.Api.V1Alpha1.WriteSchemaResponse WriteSchema(global::Authzed.Api.V1Alpha1.WriteSchemaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_WriteSchema, null, options, request);
      }
      /// <summary>
      /// Write overwrites the current Object Definitions for a Permissions System.
      ///
      /// Any Object Definitions that exist, but are not included will be deleted.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Authzed.Api.V1Alpha1.WriteSchemaResponse> WriteSchemaAsync(global::Authzed.Api.V1Alpha1.WriteSchemaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WriteSchemaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Write overwrites the current Object Definitions for a Permissions System.
      ///
      /// Any Object Definitions that exist, but are not included will be deleted.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Authzed.Api.V1Alpha1.WriteSchemaResponse> WriteSchemaAsync(global::Authzed.Api.V1Alpha1.WriteSchemaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_WriteSchema, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SchemaServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SchemaServiceClient(configuration);
      }
    }

  }
}
#endregion
