// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/v1alpha1/watchresources_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authzed.Api.V1Alpha1 {

  /// <summary>Holder for reflection information generated from authzed/api/v1alpha1/watchresources_service.proto</summary>
  public static partial class WatchresourcesServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for authzed/api/v1alpha1/watchresources_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatchresourcesServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFhdXRoemVkL2FwaS92MWFscGhhMS93YXRjaHJlc291cmNlc19zZXJ2aWNl",
            "LnByb3RvEhRhdXRoemVkLmFwaS52MWFscGhhMRocZ29vZ2xlL2FwaS9hbm5v",
            "dGF0aW9ucy5wcm90bxoXdmFsaWRhdGUvdmFsaWRhdGUucHJvdG8aGWF1dGh6",
            "ZWQvYXBpL3YxL2NvcmUucHJvdG8ilgMKFVdhdGNoUmVzb3VyY2VzUmVxdWVz",
            "dBJ6ChRyZXNvdXJjZV9vYmplY3RfdHlwZRgBIAEoCUJI+kJFckMogAEyPl4o",
            "W2Etel1bYS16MC05X117MSw2MX1bYS16MC05XS8pKlthLXpdW2EtejAtOV9d",
            "ezEsNjJ9W2EtejAtOV0kUhJyZXNvdXJjZU9iamVjdFR5cGUSRwoKcGVybWlz",
            "c2lvbhgCIAEoCUIn+kIkciIoQDIeXlthLXpdW2EtejAtOV9dezEsNjJ9W2Et",
            "ejAtOV0kUgpwZXJtaXNzaW9uEi4KE3N1YmplY3Rfb2JqZWN0X3R5cGUYAyAB",
            "KAlSEXN1YmplY3RPYmplY3RUeXBlEjoKGW9wdGlvbmFsX3N1YmplY3RfcmVs",
            "YXRpb24YBCABKAlSF29wdGlvbmFsU3ViamVjdFJlbGF0aW9uEkwKFW9wdGlv",
            "bmFsX3N0YXJ0X2N1cnNvchgFIAEoCzIYLmF1dGh6ZWQuYXBpLnYxLlplZFRv",
            "a2VuUhNvcHRpb25hbFN0YXJ0Q3Vyc29yIoQDChBQZXJtaXNzaW9uVXBkYXRl",
            "EjoKB3N1YmplY3QYASABKAsyIC5hdXRoemVkLmFwaS52MS5TdWJqZWN0UmVm",
            "ZXJlbmNlUgdzdWJqZWN0EjsKCHJlc291cmNlGAIgASgLMh8uYXV0aHplZC5h",
            "cGkudjEuT2JqZWN0UmVmZXJlbmNlUghyZXNvdXJjZRIaCghyZWxhdGlvbhgD",
            "IAEoCVIIcmVsYXRpb24SZAoSdXBkYXRlZF9wZXJtaXNzaW9uGAQgASgOMjUu",
            "YXV0aHplZC5hcGkudjFhbHBoYTEuUGVybWlzc2lvblVwZGF0ZS5QZXJtaXNz",
            "aW9uc2hpcFIRdXBkYXRlZFBlcm1pc3Npb24idQoOUGVybWlzc2lvbnNoaXAS",
            "HgoaUEVSTUlTU0lPTlNISVBfVU5TUEVDSUZJRUQQABIgChxQRVJNSVNTSU9O",
            "U0hJUF9OT19QRVJNSVNTSU9OEAESIQodUEVSTUlTU0lPTlNISVBfSEFTX1BF",
            "Uk1JU1NJT04QAiKdAQoWV2F0Y2hSZXNvdXJjZXNSZXNwb25zZRJACgd1cGRh",
            "dGVzGAEgAygLMiYuYXV0aHplZC5hcGkudjFhbHBoYTEuUGVybWlzc2lvblVw",
            "ZGF0ZVIHdXBkYXRlcxJBCg9jaGFuZ2VzX3Rocm91Z2gYAiABKAsyGC5hdXRo",
            "emVkLmFwaS52MS5aZWRUb2tlblIOY2hhbmdlc1Rocm91Z2gyqQEKFVdhdGNo",
            "UmVzb3VyY2VzU2VydmljZRKPAQoOV2F0Y2hSZXNvdXJjZXMSKy5hdXRoemVk",
            "LmFwaS52MWFscGhhMS5XYXRjaFJlc291cmNlc1JlcXVlc3QaLC5hdXRoemVk",
            "LmFwaS52MWFscGhhMS5XYXRjaFJlc291cmNlc1Jlc3BvbnNlIiCC0+STAho6",
            "ASoiFS92MWFscGhhMS9sb29rdXB3YXRjaDABQlQKGGNvbS5hdXRoemVkLmFw",
            "aS52MWFscGhhMVo4Z2l0aHViLmNvbS9hdXRoemVkL2F1dGh6ZWQtZ28vcHJv",
            "dG8vYXV0aHplZC9hcGkvdjFhbHBoYTFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Authzed.Api.V1.CoreReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1Alpha1.WatchResourcesRequest), global::Authzed.Api.V1Alpha1.WatchResourcesRequest.Parser, new[]{ "ResourceObjectType", "Permission", "SubjectObjectType", "OptionalSubjectRelation", "OptionalStartCursor" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1Alpha1.PermissionUpdate), global::Authzed.Api.V1Alpha1.PermissionUpdate.Parser, new[]{ "Subject", "Resource", "Relation", "UpdatedPermission" }, null, new[]{ typeof(global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.V1Alpha1.WatchResourcesResponse), global::Authzed.Api.V1Alpha1.WatchResourcesResponse.Parser, new[]{ "Updates", "ChangesThrough" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// WatchResourcesRequest starts a watch for specific permission updates
  /// for the given resource and subject types.
  /// </summary>
  public sealed partial class WatchResourcesRequest : pb::IMessage<WatchResourcesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchResourcesRequest> _parser = new pb::MessageParser<WatchResourcesRequest>(() => new WatchResourcesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchResourcesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1Alpha1.WatchresourcesServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesRequest(WatchResourcesRequest other) : this() {
      resourceObjectType_ = other.resourceObjectType_;
      permission_ = other.permission_;
      subjectObjectType_ = other.subjectObjectType_;
      optionalSubjectRelation_ = other.optionalSubjectRelation_;
      optionalStartCursor_ = other.optionalStartCursor_ != null ? other.optionalStartCursor_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesRequest Clone() {
      return new WatchResourcesRequest(this);
    }

    /// <summary>Field number for the "resource_object_type" field.</summary>
    public const int ResourceObjectTypeFieldNumber = 1;
    private string resourceObjectType_ = "";
    /// <summary>
    /// resource_object_type is the type of resource object for which we will
    /// watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceObjectType {
      get { return resourceObjectType_; }
      set {
        resourceObjectType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "permission" field.</summary>
    public const int PermissionFieldNumber = 2;
    private string permission_ = "";
    /// <summary>
    /// permission is the name of the permission or relation for which we will
    /// watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Permission {
      get { return permission_; }
      set {
        permission_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "subject_object_type" field.</summary>
    public const int SubjectObjectTypeFieldNumber = 3;
    private string subjectObjectType_ = "";
    /// <summary>
    /// subject_object_type is the type of the subject resource for which we will
    /// watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubjectObjectType {
      get { return subjectObjectType_; }
      set {
        subjectObjectType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "optional_subject_relation" field.</summary>
    public const int OptionalSubjectRelationFieldNumber = 4;
    private string optionalSubjectRelation_ = "";
    /// <summary>
    /// optional_subject_relation allows you to specify a group of subjects to watch
    /// for a given subject type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OptionalSubjectRelation {
      get { return optionalSubjectRelation_; }
      set {
        optionalSubjectRelation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "optional_start_cursor" field.</summary>
    public const int OptionalStartCursorFieldNumber = 5;
    private global::Authzed.Api.V1.ZedToken optionalStartCursor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken OptionalStartCursor {
      get { return optionalStartCursor_; }
      set {
        optionalStartCursor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchResourcesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchResourcesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceObjectType != other.ResourceObjectType) return false;
      if (Permission != other.Permission) return false;
      if (SubjectObjectType != other.SubjectObjectType) return false;
      if (OptionalSubjectRelation != other.OptionalSubjectRelation) return false;
      if (!object.Equals(OptionalStartCursor, other.OptionalStartCursor)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceObjectType.Length != 0) hash ^= ResourceObjectType.GetHashCode();
      if (Permission.Length != 0) hash ^= Permission.GetHashCode();
      if (SubjectObjectType.Length != 0) hash ^= SubjectObjectType.GetHashCode();
      if (OptionalSubjectRelation.Length != 0) hash ^= OptionalSubjectRelation.GetHashCode();
      if (optionalStartCursor_ != null) hash ^= OptionalStartCursor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResourceObjectType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceObjectType);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Permission);
      }
      if (SubjectObjectType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SubjectObjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OptionalSubjectRelation);
      }
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(OptionalStartCursor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResourceObjectType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceObjectType);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Permission);
      }
      if (SubjectObjectType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SubjectObjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OptionalSubjectRelation);
      }
      if (optionalStartCursor_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(OptionalStartCursor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResourceObjectType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceObjectType);
      }
      if (Permission.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Permission);
      }
      if (SubjectObjectType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubjectObjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OptionalSubjectRelation);
      }
      if (optionalStartCursor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalStartCursor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchResourcesRequest other) {
      if (other == null) {
        return;
      }
      if (other.ResourceObjectType.Length != 0) {
        ResourceObjectType = other.ResourceObjectType;
      }
      if (other.Permission.Length != 0) {
        Permission = other.Permission;
      }
      if (other.SubjectObjectType.Length != 0) {
        SubjectObjectType = other.SubjectObjectType;
      }
      if (other.OptionalSubjectRelation.Length != 0) {
        OptionalSubjectRelation = other.OptionalSubjectRelation;
      }
      if (other.optionalStartCursor_ != null) {
        if (optionalStartCursor_ == null) {
          OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
        }
        OptionalStartCursor.MergeFrom(other.OptionalStartCursor);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceObjectType = input.ReadString();
            break;
          }
          case 18: {
            Permission = input.ReadString();
            break;
          }
          case 26: {
            SubjectObjectType = input.ReadString();
            break;
          }
          case 34: {
            OptionalSubjectRelation = input.ReadString();
            break;
          }
          case 42: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResourceObjectType = input.ReadString();
            break;
          }
          case 18: {
            Permission = input.ReadString();
            break;
          }
          case 26: {
            SubjectObjectType = input.ReadString();
            break;
          }
          case 34: {
            OptionalSubjectRelation = input.ReadString();
            break;
          }
          case 42: {
            if (optionalStartCursor_ == null) {
              OptionalStartCursor = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartCursor);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// PermissionUpdate represents a single permission update for a specific
  /// subject's permissions.
  /// </summary>
  public sealed partial class PermissionUpdate : pb::IMessage<PermissionUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PermissionUpdate> _parser = new pb::MessageParser<PermissionUpdate>(() => new PermissionUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PermissionUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1Alpha1.WatchresourcesServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionUpdate(PermissionUpdate other) : this() {
      subject_ = other.subject_ != null ? other.subject_.Clone() : null;
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      relation_ = other.relation_;
      updatedPermission_ = other.updatedPermission_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionUpdate Clone() {
      return new PermissionUpdate(this);
    }

    /// <summary>Field number for the "subject" field.</summary>
    public const int SubjectFieldNumber = 1;
    private global::Authzed.Api.V1.SubjectReference subject_;
    /// <summary>
    /// subject defines the subject resource whose permissions have changed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.SubjectReference Subject {
      get { return subject_; }
      set {
        subject_ = value;
      }
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 2;
    private global::Authzed.Api.V1.ObjectReference resource_;
    /// <summary>
    /// resource defines the specific object in the system.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ObjectReference Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    /// <summary>Field number for the "relation" field.</summary>
    public const int RelationFieldNumber = 3;
    private string relation_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Relation {
      get { return relation_; }
      set {
        relation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "updated_permission" field.</summary>
    public const int UpdatedPermissionFieldNumber = 4;
    private global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship updatedPermission_ = global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship UpdatedPermission {
      get { return updatedPermission_; }
      set {
        updatedPermission_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PermissionUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PermissionUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Subject, other.Subject)) return false;
      if (!object.Equals(Resource, other.Resource)) return false;
      if (Relation != other.Relation) return false;
      if (UpdatedPermission != other.UpdatedPermission) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (subject_ != null) hash ^= Subject.GetHashCode();
      if (resource_ != null) hash ^= Resource.GetHashCode();
      if (Relation.Length != 0) hash ^= Relation.GetHashCode();
      if (UpdatedPermission != global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified) hash ^= UpdatedPermission.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (subject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subject);
      }
      if (resource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Resource);
      }
      if (Relation.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Relation);
      }
      if (UpdatedPermission != global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) UpdatedPermission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (subject_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Subject);
      }
      if (resource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Resource);
      }
      if (Relation.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Relation);
      }
      if (UpdatedPermission != global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) UpdatedPermission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (subject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subject);
      }
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      if (Relation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Relation);
      }
      if (UpdatedPermission != global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpdatedPermission);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PermissionUpdate other) {
      if (other == null) {
        return;
      }
      if (other.subject_ != null) {
        if (subject_ == null) {
          Subject = new global::Authzed.Api.V1.SubjectReference();
        }
        Subject.MergeFrom(other.Subject);
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::Authzed.Api.V1.ObjectReference();
        }
        Resource.MergeFrom(other.Resource);
      }
      if (other.Relation.Length != 0) {
        Relation = other.Relation;
      }
      if (other.UpdatedPermission != global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship.Unspecified) {
        UpdatedPermission = other.UpdatedPermission;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
          case 18: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 26: {
            Relation = input.ReadString();
            break;
          }
          case 32: {
            UpdatedPermission = (global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
          case 18: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 26: {
            Relation = input.ReadString();
            break;
          }
          case 32: {
            UpdatedPermission = (global::Authzed.Api.V1Alpha1.PermissionUpdate.Types.Permissionship) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PermissionUpdate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// todo: work this into the v1 core API at some point since it's used
      /// across services.
      /// </summary>
      public enum Permissionship {
        [pbr::OriginalName("PERMISSIONSHIP_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("PERMISSIONSHIP_NO_PERMISSION")] NoPermission = 1,
        [pbr::OriginalName("PERMISSIONSHIP_HAS_PERMISSION")] HasPermission = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// WatchResourcesResponse enumerates the list of permission updates that have
  /// occurred as a result of one or more relationship updates.
  /// </summary>
  public sealed partial class WatchResourcesResponse : pb::IMessage<WatchResourcesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchResourcesResponse> _parser = new pb::MessageParser<WatchResourcesResponse>(() => new WatchResourcesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchResourcesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.V1Alpha1.WatchresourcesServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesResponse(WatchResourcesResponse other) : this() {
      updates_ = other.updates_.Clone();
      changesThrough_ = other.changesThrough_ != null ? other.changesThrough_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchResourcesResponse Clone() {
      return new WatchResourcesResponse(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Authzed.Api.V1Alpha1.PermissionUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Authzed.Api.V1Alpha1.PermissionUpdate.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.V1Alpha1.PermissionUpdate> updates_ = new pbc::RepeatedField<global::Authzed.Api.V1Alpha1.PermissionUpdate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.V1Alpha1.PermissionUpdate> Updates {
      get { return updates_; }
    }

    /// <summary>Field number for the "changes_through" field.</summary>
    public const int ChangesThroughFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken changesThrough_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken ChangesThrough {
      get { return changesThrough_; }
      set {
        changesThrough_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchResourcesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchResourcesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      if (!object.Equals(ChangesThrough, other.ChangesThrough)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (changesThrough_ != null) hash ^= ChangesThrough.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      updates_.WriteTo(output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      updates_.WriteTo(ref output, _repeated_updates_codec);
      if (changesThrough_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangesThrough);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (changesThrough_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangesThrough);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchResourcesResponse other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      if (other.changesThrough_ != null) {
        if (changesThrough_ == null) {
          ChangesThrough = new global::Authzed.Api.V1.ZedToken();
        }
        ChangesThrough.MergeFrom(other.ChangesThrough);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            updates_.AddEntriesFrom(ref input, _repeated_updates_codec);
            break;
          }
          case 18: {
            if (changesThrough_ == null) {
              ChangesThrough = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(ChangesThrough);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
