// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/materialize/v0/watchpermissions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Authzed.Api.Materialize.V0 {

  /// <summary>Holder for reflection information generated from authzed/api/materialize/v0/watchpermissions.proto</summary>
  public static partial class WatchpermissionsReflection {

    #region Descriptor
    /// <summary>File descriptor for authzed/api/materialize/v0/watchpermissions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WatchpermissionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFhdXRoemVkL2FwaS9tYXRlcmlhbGl6ZS92MC93YXRjaHBlcm1pc3Npb25z",
            "LnByb3RvEhphdXRoemVkLmFwaS5tYXRlcmlhbGl6ZS52MBoZYXV0aHplZC9h",
            "cGkvdjEvY29yZS5wcm90byK8AQoXV2F0Y2hQZXJtaXNzaW9uc1JlcXVlc3QS",
            "TwoLcGVybWlzc2lvbnMYASADKAsyLS5hdXRoemVkLmFwaS5tYXRlcmlhbGl6",
            "ZS52MC5XYXRjaGVkUGVybWlzc2lvblILcGVybWlzc2lvbnMSUAoXb3B0aW9u",
            "YWxfc3RhcnRpbmdfYWZ0ZXIYAiABKAsyGC5hdXRoemVkLmFwaS52MS5aZWRU",
            "b2tlblIVb3B0aW9uYWxTdGFydGluZ0FmdGVyIrcBChFXYXRjaGVkUGVybWlz",
            "c2lvbhIjCg1yZXNvdXJjZV90eXBlGAEgASgJUgxyZXNvdXJjZVR5cGUSHgoK",
            "cGVybWlzc2lvbhgCIAEoCVIKcGVybWlzc2lvbhIhCgxzdWJqZWN0X3R5cGUY",
            "AyABKAlSC3N1YmplY3RUeXBlEjoKGW9wdGlvbmFsX3N1YmplY3RfcmVsYXRp",
            "b24YBCABKAlSF29wdGlvbmFsU3ViamVjdFJlbGF0aW9uIrkBChhXYXRjaFBl",
            "cm1pc3Npb25zUmVzcG9uc2USRgoGY2hhbmdlGAEgASgLMiwuYXV0aHplZC5h",
            "cGkubWF0ZXJpYWxpemUudjAuUGVybWlzc2lvbkNoYW5nZUgAUgZjaGFuZ2US",
            "SQoSY29tcGxldGVkX3JldmlzaW9uGAIgASgLMhguYXV0aHplZC5hcGkudjEu",
            "WmVkVG9rZW5IAFIRY29tcGxldGVkUmV2aXNpb25CCgoIcmVzcG9uc2Ui6QMK",
            "EFBlcm1pc3Npb25DaGFuZ2USNAoIcmV2aXNpb24YASABKAsyGC5hdXRoemVk",
            "LmFwaS52MS5aZWRUb2tlblIIcmV2aXNpb24SOwoIcmVzb3VyY2UYAiABKAsy",
            "Hy5hdXRoemVkLmFwaS52MS5PYmplY3RSZWZlcmVuY2VSCHJlc291cmNlEh4K",
            "CnBlcm1pc3Npb24YAyABKAlSCnBlcm1pc3Npb24SOgoHc3ViamVjdBgEIAEo",
            "CzIgLmF1dGh6ZWQuYXBpLnYxLlN1YmplY3RSZWZlcmVuY2VSB3N1YmplY3QS",
            "YwoOcGVybWlzc2lvbnNoaXAYBSABKA4yOy5hdXRoemVkLmFwaS5tYXRlcmlh",
            "bGl6ZS52MC5QZXJtaXNzaW9uQ2hhbmdlLlBlcm1pc3Npb25zaGlwUg5wZXJt",
            "aXNzaW9uc2hpcCKgAQoOUGVybWlzc2lvbnNoaXASHgoaUEVSTUlTU0lPTlNI",
            "SVBfVU5TUEVDSUZJRUQQABIgChxQRVJNSVNTSU9OU0hJUF9OT19QRVJNSVNT",
            "SU9OEAESIQodUEVSTUlTU0lPTlNISVBfSEFTX1BFUk1JU1NJT04QAhIpCiVQ",
            "RVJNSVNTSU9OU0hJUF9DT05ESVRJT05BTF9QRVJNSVNTSU9OEAMynQEKF1dh",
            "dGNoUGVybWlzc2lvbnNTZXJ2aWNlEoEBChBXYXRjaFBlcm1pc3Npb25zEjMu",
            "YXV0aHplZC5hcGkubWF0ZXJpYWxpemUudjAuV2F0Y2hQZXJtaXNzaW9uc1Jl",
            "cXVlc3QaNC5hdXRoemVkLmFwaS5tYXRlcmlhbGl6ZS52MC5XYXRjaFBlcm1p",
            "c3Npb25zUmVzcG9uc2UiADABQmIKHmNvbS5hdXRoemVkLmFwaS5tYXRlcmlh",
            "bGl6ZS52MFABWj5naXRodWIuY29tL2F1dGh6ZWQvYXV0aHplZC1nby9wcm90",
            "by9hdXRoemVkL2FwaS9tYXRlcmlhbGl6ZS92MGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Authzed.Api.V1.CoreReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.Materialize.V0.WatchPermissionsRequest), global::Authzed.Api.Materialize.V0.WatchPermissionsRequest.Parser, new[]{ "Permissions", "OptionalStartingAfter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.Materialize.V0.WatchedPermission), global::Authzed.Api.Materialize.V0.WatchedPermission.Parser, new[]{ "ResourceType", "Permission", "SubjectType", "OptionalSubjectRelation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.Materialize.V0.WatchPermissionsResponse), global::Authzed.Api.Materialize.V0.WatchPermissionsResponse.Parser, new[]{ "Change", "CompletedRevision" }, new[]{ "Response" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Authzed.Api.Materialize.V0.PermissionChange), global::Authzed.Api.Materialize.V0.PermissionChange.Parser, new[]{ "Revision", "Resource", "Permission", "Subject", "Permissionship" }, null, new[]{ typeof(global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class WatchPermissionsRequest : pb::IMessage<WatchPermissionsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchPermissionsRequest> _parser = new pb::MessageParser<WatchPermissionsRequest>(() => new WatchPermissionsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchPermissionsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.Materialize.V0.WatchpermissionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsRequest(WatchPermissionsRequest other) : this() {
      permissions_ = other.permissions_.Clone();
      optionalStartingAfter_ = other.optionalStartingAfter_ != null ? other.optionalStartingAfter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsRequest Clone() {
      return new WatchPermissionsRequest(this);
    }

    /// <summary>Field number for the "permissions" field.</summary>
    public const int PermissionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Authzed.Api.Materialize.V0.WatchedPermission> _repeated_permissions_codec
        = pb::FieldCodec.ForMessage(10, global::Authzed.Api.Materialize.V0.WatchedPermission.Parser);
    private readonly pbc::RepeatedField<global::Authzed.Api.Materialize.V0.WatchedPermission> permissions_ = new pbc::RepeatedField<global::Authzed.Api.Materialize.V0.WatchedPermission>();
    /// <summary>
    /// permissions is a list of permissions to watch for changes. At least one permission must be specified, and it must
    /// be a subset or equal to the permissions that were enabled for the service.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Authzed.Api.Materialize.V0.WatchedPermission> Permissions {
      get { return permissions_; }
    }

    /// <summary>Field number for the "optional_starting_after" field.</summary>
    public const int OptionalStartingAfterFieldNumber = 2;
    private global::Authzed.Api.V1.ZedToken optionalStartingAfter_;
    /// <summary>
    /// optional_starting_after is the revision token to start watching from. If not provided, the stream
    /// will start from the current revision at the moment of the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken OptionalStartingAfter {
      get { return optionalStartingAfter_; }
      set {
        optionalStartingAfter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchPermissionsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchPermissionsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!permissions_.Equals(other.permissions_)) return false;
      if (!object.Equals(OptionalStartingAfter, other.OptionalStartingAfter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= permissions_.GetHashCode();
      if (optionalStartingAfter_ != null) hash ^= OptionalStartingAfter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      permissions_.WriteTo(output, _repeated_permissions_codec);
      if (optionalStartingAfter_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartingAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      permissions_.WriteTo(ref output, _repeated_permissions_codec);
      if (optionalStartingAfter_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OptionalStartingAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += permissions_.CalculateSize(_repeated_permissions_codec);
      if (optionalStartingAfter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OptionalStartingAfter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchPermissionsRequest other) {
      if (other == null) {
        return;
      }
      permissions_.Add(other.permissions_);
      if (other.optionalStartingAfter_ != null) {
        if (optionalStartingAfter_ == null) {
          OptionalStartingAfter = new global::Authzed.Api.V1.ZedToken();
        }
        OptionalStartingAfter.MergeFrom(other.OptionalStartingAfter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            permissions_.AddEntriesFrom(input, _repeated_permissions_codec);
            break;
          }
          case 18: {
            if (optionalStartingAfter_ == null) {
              OptionalStartingAfter = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartingAfter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            permissions_.AddEntriesFrom(ref input, _repeated_permissions_codec);
            break;
          }
          case 18: {
            if (optionalStartingAfter_ == null) {
              OptionalStartingAfter = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(OptionalStartingAfter);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WatchedPermission : pb::IMessage<WatchedPermission>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchedPermission> _parser = new pb::MessageParser<WatchedPermission>(() => new WatchedPermission());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchedPermission> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.Materialize.V0.WatchpermissionsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchedPermission() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchedPermission(WatchedPermission other) : this() {
      resourceType_ = other.resourceType_;
      permission_ = other.permission_;
      subjectType_ = other.subjectType_;
      optionalSubjectRelation_ = other.optionalSubjectRelation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchedPermission Clone() {
      return new WatchedPermission(this);
    }

    /// <summary>Field number for the "resource_type" field.</summary>
    public const int ResourceTypeFieldNumber = 1;
    private string resourceType_ = "";
    /// <summary>
    /// resource_type is the type of the resource to watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceType {
      get { return resourceType_; }
      set {
        resourceType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "permission" field.</summary>
    public const int PermissionFieldNumber = 2;
    private string permission_ = "";
    /// <summary>
    /// permission is the permission to watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Permission {
      get { return permission_; }
      set {
        permission_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "subject_type" field.</summary>
    public const int SubjectTypeFieldNumber = 3;
    private string subjectType_ = "";
    /// <summary>
    /// subject_type is the type of the subject to watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubjectType {
      get { return subjectType_; }
      set {
        subjectType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "optional_subject_relation" field.</summary>
    public const int OptionalSubjectRelationFieldNumber = 4;
    private string optionalSubjectRelation_ = "";
    /// <summary>
    /// optional_subject_relation is the relation on the subject to watch for changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OptionalSubjectRelation {
      get { return optionalSubjectRelation_; }
      set {
        optionalSubjectRelation_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchedPermission);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchedPermission other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceType != other.ResourceType) return false;
      if (Permission != other.Permission) return false;
      if (SubjectType != other.SubjectType) return false;
      if (OptionalSubjectRelation != other.OptionalSubjectRelation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceType.Length != 0) hash ^= ResourceType.GetHashCode();
      if (Permission.Length != 0) hash ^= Permission.GetHashCode();
      if (SubjectType.Length != 0) hash ^= SubjectType.GetHashCode();
      if (OptionalSubjectRelation.Length != 0) hash ^= OptionalSubjectRelation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResourceType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceType);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Permission);
      }
      if (SubjectType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SubjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OptionalSubjectRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResourceType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceType);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Permission);
      }
      if (SubjectType.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SubjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OptionalSubjectRelation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResourceType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceType);
      }
      if (Permission.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Permission);
      }
      if (SubjectType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubjectType);
      }
      if (OptionalSubjectRelation.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OptionalSubjectRelation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchedPermission other) {
      if (other == null) {
        return;
      }
      if (other.ResourceType.Length != 0) {
        ResourceType = other.ResourceType;
      }
      if (other.Permission.Length != 0) {
        Permission = other.Permission;
      }
      if (other.SubjectType.Length != 0) {
        SubjectType = other.SubjectType;
      }
      if (other.OptionalSubjectRelation.Length != 0) {
        OptionalSubjectRelation = other.OptionalSubjectRelation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceType = input.ReadString();
            break;
          }
          case 18: {
            Permission = input.ReadString();
            break;
          }
          case 26: {
            SubjectType = input.ReadString();
            break;
          }
          case 34: {
            OptionalSubjectRelation = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResourceType = input.ReadString();
            break;
          }
          case 18: {
            Permission = input.ReadString();
            break;
          }
          case 26: {
            SubjectType = input.ReadString();
            break;
          }
          case 34: {
            OptionalSubjectRelation = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class WatchPermissionsResponse : pb::IMessage<WatchPermissionsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WatchPermissionsResponse> _parser = new pb::MessageParser<WatchPermissionsResponse>(() => new WatchPermissionsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WatchPermissionsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.Materialize.V0.WatchpermissionsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsResponse(WatchPermissionsResponse other) : this() {
      switch (other.ResponseCase) {
        case ResponseOneofCase.Change:
          Change = other.Change.Clone();
          break;
        case ResponseOneofCase.CompletedRevision:
          CompletedRevision = other.CompletedRevision.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WatchPermissionsResponse Clone() {
      return new WatchPermissionsResponse(this);
    }

    /// <summary>Field number for the "change" field.</summary>
    public const int ChangeFieldNumber = 1;
    /// <summary>
    /// change is the computed permission delta that has occurred as result of a mutation in origin SpiceDB.
    /// The consumer should apply this change to the current state of the computed permissions in their target system.
    /// Once an event arrives with completed_revision instead, the consumer shall consider there are not more changes
    /// originating from that revision.
    ///
    /// The consumer should keep track of the revision in order to resume streaming in the event of consumer restarts.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.Materialize.V0.PermissionChange Change {
      get { return responseCase_ == ResponseOneofCase.Change ? (global::Authzed.Api.Materialize.V0.PermissionChange) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Change;
      }
    }

    /// <summary>Field number for the "completed_revision" field.</summary>
    public const int CompletedRevisionFieldNumber = 2;
    /// <summary>
    /// completed_revision is the revision token that indicates all changes originating from a revision have been
    /// streamed and thus the revision should be considered completed. It may also be
    /// received without accompanying set of changes, indicating that a mutation in the origin SpiceDB cluster did
    /// not yield any effective changes in the computed permissions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken CompletedRevision {
      get { return responseCase_ == ResponseOneofCase.CompletedRevision ? (global::Authzed.Api.V1.ZedToken) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.CompletedRevision;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      Change = 1,
      CompletedRevision = 2,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WatchPermissionsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WatchPermissionsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Change, other.Change)) return false;
      if (!object.Equals(CompletedRevision, other.CompletedRevision)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (responseCase_ == ResponseOneofCase.Change) hash ^= Change.GetHashCode();
      if (responseCase_ == ResponseOneofCase.CompletedRevision) hash ^= CompletedRevision.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (responseCase_ == ResponseOneofCase.Change) {
        output.WriteRawTag(10);
        output.WriteMessage(Change);
      }
      if (responseCase_ == ResponseOneofCase.CompletedRevision) {
        output.WriteRawTag(18);
        output.WriteMessage(CompletedRevision);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (responseCase_ == ResponseOneofCase.Change) {
        output.WriteRawTag(10);
        output.WriteMessage(Change);
      }
      if (responseCase_ == ResponseOneofCase.CompletedRevision) {
        output.WriteRawTag(18);
        output.WriteMessage(CompletedRevision);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (responseCase_ == ResponseOneofCase.Change) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Change);
      }
      if (responseCase_ == ResponseOneofCase.CompletedRevision) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CompletedRevision);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WatchPermissionsResponse other) {
      if (other == null) {
        return;
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.Change:
          if (Change == null) {
            Change = new global::Authzed.Api.Materialize.V0.PermissionChange();
          }
          Change.MergeFrom(other.Change);
          break;
        case ResponseOneofCase.CompletedRevision:
          if (CompletedRevision == null) {
            CompletedRevision = new global::Authzed.Api.V1.ZedToken();
          }
          CompletedRevision.MergeFrom(other.CompletedRevision);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Authzed.Api.Materialize.V0.PermissionChange subBuilder = new global::Authzed.Api.Materialize.V0.PermissionChange();
            if (responseCase_ == ResponseOneofCase.Change) {
              subBuilder.MergeFrom(Change);
            }
            input.ReadMessage(subBuilder);
            Change = subBuilder;
            break;
          }
          case 18: {
            global::Authzed.Api.V1.ZedToken subBuilder = new global::Authzed.Api.V1.ZedToken();
            if (responseCase_ == ResponseOneofCase.CompletedRevision) {
              subBuilder.MergeFrom(CompletedRevision);
            }
            input.ReadMessage(subBuilder);
            CompletedRevision = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Authzed.Api.Materialize.V0.PermissionChange subBuilder = new global::Authzed.Api.Materialize.V0.PermissionChange();
            if (responseCase_ == ResponseOneofCase.Change) {
              subBuilder.MergeFrom(Change);
            }
            input.ReadMessage(subBuilder);
            Change = subBuilder;
            break;
          }
          case 18: {
            global::Authzed.Api.V1.ZedToken subBuilder = new global::Authzed.Api.V1.ZedToken();
            if (responseCase_ == ResponseOneofCase.CompletedRevision) {
              subBuilder.MergeFrom(CompletedRevision);
            }
            input.ReadMessage(subBuilder);
            CompletedRevision = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PermissionChange : pb::IMessage<PermissionChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PermissionChange> _parser = new pb::MessageParser<PermissionChange>(() => new PermissionChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PermissionChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Authzed.Api.Materialize.V0.WatchpermissionsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionChange(PermissionChange other) : this() {
      revision_ = other.revision_ != null ? other.revision_.Clone() : null;
      resource_ = other.resource_ != null ? other.resource_.Clone() : null;
      permission_ = other.permission_;
      subject_ = other.subject_ != null ? other.subject_.Clone() : null;
      permissionship_ = other.permissionship_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PermissionChange Clone() {
      return new PermissionChange(this);
    }

    /// <summary>Field number for the "revision" field.</summary>
    public const int RevisionFieldNumber = 1;
    private global::Authzed.Api.V1.ZedToken revision_;
    /// <summary>
    /// revision represents the revision at which the change occurred.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ZedToken Revision {
      get { return revision_; }
      set {
        revision_ = value;
      }
    }

    /// <summary>Field number for the "resource" field.</summary>
    public const int ResourceFieldNumber = 2;
    private global::Authzed.Api.V1.ObjectReference resource_;
    /// <summary>
    /// resource is the resource that the permission change is related to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.ObjectReference Resource {
      get { return resource_; }
      set {
        resource_ = value;
      }
    }

    /// <summary>Field number for the "permission" field.</summary>
    public const int PermissionFieldNumber = 3;
    private string permission_ = "";
    /// <summary>
    /// permission is the permission that has changed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Permission {
      get { return permission_; }
      set {
        permission_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "subject" field.</summary>
    public const int SubjectFieldNumber = 4;
    private global::Authzed.Api.V1.SubjectReference subject_;
    /// <summary>
    /// subject is the subject that the permission change is related to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.V1.SubjectReference Subject {
      get { return subject_; }
      set {
        subject_ = value;
      }
    }

    /// <summary>Field number for the "permissionship" field.</summary>
    public const int PermissionshipFieldNumber = 5;
    private global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship permissionship_ = global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified;
    /// <summary>
    /// permissionship is the new permissionship of the subject over the resource after the change.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship Permissionship {
      get { return permissionship_; }
      set {
        permissionship_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PermissionChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PermissionChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Revision, other.Revision)) return false;
      if (!object.Equals(Resource, other.Resource)) return false;
      if (Permission != other.Permission) return false;
      if (!object.Equals(Subject, other.Subject)) return false;
      if (Permissionship != other.Permissionship) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (revision_ != null) hash ^= Revision.GetHashCode();
      if (resource_ != null) hash ^= Resource.GetHashCode();
      if (Permission.Length != 0) hash ^= Permission.GetHashCode();
      if (subject_ != null) hash ^= Subject.GetHashCode();
      if (Permissionship != global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified) hash ^= Permissionship.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (revision_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Revision);
      }
      if (resource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Resource);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Permission);
      }
      if (subject_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Subject);
      }
      if (Permissionship != global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Permissionship);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (revision_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Revision);
      }
      if (resource_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Resource);
      }
      if (Permission.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Permission);
      }
      if (subject_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Subject);
      }
      if (Permissionship != global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Permissionship);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (revision_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Revision);
      }
      if (resource_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resource);
      }
      if (Permission.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Permission);
      }
      if (subject_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Subject);
      }
      if (Permissionship != global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Permissionship);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PermissionChange other) {
      if (other == null) {
        return;
      }
      if (other.revision_ != null) {
        if (revision_ == null) {
          Revision = new global::Authzed.Api.V1.ZedToken();
        }
        Revision.MergeFrom(other.Revision);
      }
      if (other.resource_ != null) {
        if (resource_ == null) {
          Resource = new global::Authzed.Api.V1.ObjectReference();
        }
        Resource.MergeFrom(other.Resource);
      }
      if (other.Permission.Length != 0) {
        Permission = other.Permission;
      }
      if (other.subject_ != null) {
        if (subject_ == null) {
          Subject = new global::Authzed.Api.V1.SubjectReference();
        }
        Subject.MergeFrom(other.Subject);
      }
      if (other.Permissionship != global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship.Unspecified) {
        Permissionship = other.Permissionship;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (revision_ == null) {
              Revision = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(Revision);
            break;
          }
          case 18: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 26: {
            Permission = input.ReadString();
            break;
          }
          case 34: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
          case 40: {
            Permissionship = (global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (revision_ == null) {
              Revision = new global::Authzed.Api.V1.ZedToken();
            }
            input.ReadMessage(Revision);
            break;
          }
          case 18: {
            if (resource_ == null) {
              Resource = new global::Authzed.Api.V1.ObjectReference();
            }
            input.ReadMessage(Resource);
            break;
          }
          case 26: {
            Permission = input.ReadString();
            break;
          }
          case 34: {
            if (subject_ == null) {
              Subject = new global::Authzed.Api.V1.SubjectReference();
            }
            input.ReadMessage(Subject);
            break;
          }
          case 40: {
            Permissionship = (global::Authzed.Api.Materialize.V0.PermissionChange.Types.Permissionship) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PermissionChange message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Permissionship {
        [pbr::OriginalName("PERMISSIONSHIP_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("PERMISSIONSHIP_NO_PERMISSION")] NoPermission = 1,
        [pbr::OriginalName("PERMISSIONSHIP_HAS_PERMISSION")] HasPermission = 2,
        [pbr::OriginalName("PERMISSIONSHIP_CONDITIONAL_PERMISSION")] ConditionalPermission = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
