// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: authzed/api/materialize/v0/watchpermissions.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Authzed.Api.Materialize.V0 {
  public static partial class WatchPermissionsService
  {
    static readonly string __ServiceName = "authzed.api.materialize.v0.WatchPermissionsService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.Materialize.V0.WatchPermissionsRequest> __Marshaller_authzed_api_materialize_v0_WatchPermissionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.Materialize.V0.WatchPermissionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Authzed.Api.Materialize.V0.WatchPermissionsResponse> __Marshaller_authzed_api_materialize_v0_WatchPermissionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Authzed.Api.Materialize.V0.WatchPermissionsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Authzed.Api.Materialize.V0.WatchPermissionsRequest, global::Authzed.Api.Materialize.V0.WatchPermissionsResponse> __Method_WatchPermissions = new grpc::Method<global::Authzed.Api.Materialize.V0.WatchPermissionsRequest, global::Authzed.Api.Materialize.V0.WatchPermissionsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "WatchPermissions",
        __Marshaller_authzed_api_materialize_v0_WatchPermissionsRequest,
        __Marshaller_authzed_api_materialize_v0_WatchPermissionsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Authzed.Api.Materialize.V0.WatchpermissionsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WatchPermissionsService</summary>
    [grpc::BindServiceMethod(typeof(WatchPermissionsService), "BindService")]
    public abstract partial class WatchPermissionsServiceBase
    {
      /// <summary>
      /// WatchPermissions returns a stream of PermissionChange events for the given permissions.
      ///
      /// WatchPermissions is a long-running RPC, and will stream events until the client
      /// closes the connection or the server terminates the stream. The consumer is responsible of
      /// keeping track of the last seen revision and resuming the stream from that point in the event
      /// of disconnection or client-side restarts.
      ///
      /// The API does not offer a sharding mechanism and thus there should only be one consumer per target system.
      /// Implementing an active-active HA consumer setup over the same target system will require coordinating which
      /// revisions have been consumed in order to prevent transitioning to an inconsistent state.
      ///
      /// Usage of WatchPermissions requires to be explicitly enabled on the service, including the permissions to be
      /// watched. It requires more resources and is less performant than WatchPermissionsSets. It's usage
      /// is only recommended when performing the set intersections of WatchPermissionSets in the client side is not viable
      /// or there is a strict application requirement to use consume the computed permissions.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task WatchPermissions(global::Authzed.Api.Materialize.V0.WatchPermissionsRequest request, grpc::IServerStreamWriter<global::Authzed.Api.Materialize.V0.WatchPermissionsResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WatchPermissionsService</summary>
    public partial class WatchPermissionsServiceClient : grpc::ClientBase<WatchPermissionsServiceClient>
    {
      /// <summary>Creates a new client for WatchPermissionsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WatchPermissionsServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WatchPermissionsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WatchPermissionsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WatchPermissionsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WatchPermissionsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// WatchPermissions returns a stream of PermissionChange events for the given permissions.
      ///
      /// WatchPermissions is a long-running RPC, and will stream events until the client
      /// closes the connection or the server terminates the stream. The consumer is responsible of
      /// keeping track of the last seen revision and resuming the stream from that point in the event
      /// of disconnection or client-side restarts.
      ///
      /// The API does not offer a sharding mechanism and thus there should only be one consumer per target system.
      /// Implementing an active-active HA consumer setup over the same target system will require coordinating which
      /// revisions have been consumed in order to prevent transitioning to an inconsistent state.
      ///
      /// Usage of WatchPermissions requires to be explicitly enabled on the service, including the permissions to be
      /// watched. It requires more resources and is less performant than WatchPermissionsSets. It's usage
      /// is only recommended when performing the set intersections of WatchPermissionSets in the client side is not viable
      /// or there is a strict application requirement to use consume the computed permissions.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Authzed.Api.Materialize.V0.WatchPermissionsResponse> WatchPermissions(global::Authzed.Api.Materialize.V0.WatchPermissionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return WatchPermissions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// WatchPermissions returns a stream of PermissionChange events for the given permissions.
      ///
      /// WatchPermissions is a long-running RPC, and will stream events until the client
      /// closes the connection or the server terminates the stream. The consumer is responsible of
      /// keeping track of the last seen revision and resuming the stream from that point in the event
      /// of disconnection or client-side restarts.
      ///
      /// The API does not offer a sharding mechanism and thus there should only be one consumer per target system.
      /// Implementing an active-active HA consumer setup over the same target system will require coordinating which
      /// revisions have been consumed in order to prevent transitioning to an inconsistent state.
      ///
      /// Usage of WatchPermissions requires to be explicitly enabled on the service, including the permissions to be
      /// watched. It requires more resources and is less performant than WatchPermissionsSets. It's usage
      /// is only recommended when performing the set intersections of WatchPermissionSets in the client side is not viable
      /// or there is a strict application requirement to use consume the computed permissions.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Authzed.Api.Materialize.V0.WatchPermissionsResponse> WatchPermissions(global::Authzed.Api.Materialize.V0.WatchPermissionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_WatchPermissions, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override WatchPermissionsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WatchPermissionsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(WatchPermissionsServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_WatchPermissions, serviceImpl.WatchPermissions).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WatchPermissionsServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_WatchPermissions, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Authzed.Api.Materialize.V0.WatchPermissionsRequest, global::Authzed.Api.Materialize.V0.WatchPermissionsResponse>(serviceImpl.WatchPermissions));
    }

  }
}
#endregion
