---
name: "Test"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches: ["*"]
    types:
      # NOTE: these are the defaults
      - opened
      - synchronize
      - reopened
      # NOTE: we add this to let the conversion from draft trigger the workflows
      - ready_for_review
jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: '8.x'
      - uses: "authzed/action-spicedb@v1"
        with:
          version: "latest"
      - run: "dotnet test"
